name: autofix.ci
on:
  pull_request:
  push:
    branches: ["main"]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.1"
      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest
      - name: Run goimports on api directory
        run: |
          cd api
          goimports -w .
      - name: Run goimports on extractor directory
        run: |
          cd extractor
          goimports -w .
      - uses: autofix-ci/action@dd55f44df8f7cdb7a6bf74c78677eb8acd40cd0a
